README.md, client/README.md, package.json, server/README.md
Consolidate documentation and make it easier for new engineers to get started with our codebase
=> Improve documentation

README.md
Readme updated line:
git clone https://github.com/sfbrigade/project-compass.git > git clone https://github.com/sfbrigade/compass.git
=> Updated ReadMe Git Clone Link

README.md, src/backend/auth/adapter.ts, src/backend/context.ts, src/backend/routers/_app.ts, src/backend/routers/admins.test.ts, src/backend/routers/admins.ts, src/backend/routers/users.ts, src/backend/tests/fixtures/get-test-server.ts, src/backend/tests/seed.ts, src/backend/trpc.ts, src/client/lib/protected-page.tsx, src/pages/admin/index.tsx, src/pages/admin/postgres.tsx
Closes https://github.com/sfbrigade/compass/issues/73.
Demo:
https://github.com/sfbrigade/compass/assets/7410405/a640ef77-13c7-46dc-bda3-c727805b2667
=> Add admin framework

terraform/compass_module/main.tf, terraform/staging/main.tf
=> Add s3 backend to Terraform for managing its state in the cloud

ava.config.js, src/backend/tests/fixtures/get-test-minio.ts
Handle paths with spaces and increase Ava timeout
=> Fix running tests locally

src/backend/auth/adapter.ts, src/backend/db/migrations/1_initial-migrations.sql, src/backend/routers/files.ts, src/backend/routers/paras.test.ts, src/backend/routers/paras.ts, src/backend/routers/students.ts, src/backend/routers/users.ts, src/backend/tests/seed.ts, src/backend/trpc.ts
Also rename 'protectedProcedure' to 'authenticatedProcedure' to better clarify intent.
Use 'authenticatedProcedures' everywhere instead of 'procedure'.
=> Replace 'para' and 'case_manager' roles with 'staff'

ava.config.js, package-lock.json, package.json, src/backend/context.ts, src/backend/db/lib/get-db.ts, src/backend/db/lib/migrate.ts, src/backend/db/lib/reset.ts, src/backend/routers/admin.test.ts, src/backend/routers/file.test.ts, src/backend/routers/para.test.ts, src/backend/routers/student.test.ts, src/backend/routers/user.test.ts, src/backend/scripts/migrate-database.ts, src/backend/scripts/reset-database.ts, src/backend/tests/fixtures/get-test-database.ts, src/backend/tests/fixtures/get-test-server.ts, src/client/lib/trpc.ts, src/components/case_manager/MyParas.tsx, src/components/case_manager/MyStudents.tsx, src/components/case_manager/PersonCreationForm.tsx, src/pages/_app.tsx, src/pages/api/auth/[...nextauth].ts, src/pages/api/trpc/[trpc].ts, src/pages/files.tsx, src/pages/index.tsx, src/pages/paras/[user_id].tsx, src/pages/students/[student_id].tsx, tsconfig.json
=> Use consistent path aliases

src/backend/routers/para.test.ts, src/backend/routers/student.test.ts, src/backend/tests/fixtures/get-test-server.ts, src/backend/tests/seed.ts
Use the case_manager for tests where it makes sense.
=> Add a case_manager and a student to the seed data, and remove para2.

src/backend/routers/student.ts, src/components/case_manager/MyStudents.tsx, src/pages/cmDashboard.tsx, src/pages/students/[student_id].tsx
Items updated:
1. In [student_id].tsx, change mutate to mutateAsync similar to [user_id].tsx in the para folder.
2. Rename the MyStudentsPage function to MyStudents and make sure all routes using this is corrected.
3. Convert student email to lowercase when adding into the DB.
student.test.ts doesn't seem to need to be updated.
=> Update student flow

src/components/case_manager/PersonTable.tsx
#109  Added search to table, removed row selection and made whole row clickable as requested by design team.
=> Search Function #109

src/components/Goal.tsx, src/components/Subgoal.tsx, src/components/para_trials/counter.tsx, src/components/para_trials/progressBar.tsx, src/components/para_trials/taskCard.tsx, src/components/para_trials/timer.tsx, src/components/para_trials/timerInputPad.tsx, src/pages/students/iep.tsx
These were the following changes:-
1. Removed React.FC from all components.
2.  Added the type props for the corresponding components.
3.  It was not necessary to change component names.
Add comments if further changes are necessary.
=> Removed React.FC from components

src/components/NavBar.tsx, src/pages/index.tsx
Removed tRPC user checks, replaced with useSession hook to check auth status, slightly improved navbar while we were in there
=> Fix pre-login 401 error

src/backend/routers/student.ts, src/components/layout/Layout.module.css, src/components/layout/Layout.tsx, src/pages/benchmarks/[benchmark_id]/index.tsx, src/pages/benchmarks/[benchmark_id]/instructions.tsx, src/pages/benchmarks/[benchmark_id]/studentprofile.tsx, src/pages/benchmarks/index.tsx, src/styles/Box.module.css, src/styles/Button.module.css, src/styles/Typography.module.css
=> Added student profile and instructions pages

terraform/gcs/cloud_run.tf, terraform/gcs/cloud_storage.tf, terraform/gcs/secrets.tf
Depends on https://github.com/sfbrigade/compass/pull/171.
=> Add user data bucket setup

src/backend/db/migrations/1_initial-migrations.sql, src/backend/db/zapatos/schema.d.ts, src/backend/routers/iep.ts, src/components/counter/counter.tsx, src/components/paraTrials/Paratrials.module.css, src/pages/benchmarks/[benchmark_id]/index.tsx, src/pages/benchmarks/[benchmark_id]/review.tsx, src/styles/Typography.module.css, src/styles/globals.css
=> Changed data collection to take success/unsuccess.

src/backend/routers/iep.ts, src/components/subgoal/Subgoal.tsx
=> Quick bug fix to prevent multiple assignments of benchmarks.

src/components/table/table.tsx, src/pages/staff/[user_id].tsx
#184 fixed pararouting 
- Staff page - clicking on a para should take the cm to the individual para page.
-  In the individual para page, change CM Dashboard to return to Staff List.
=> fixed para routing

src/backend/auth/options.ts, src/middleware.ts
Closes https://github.com/sfbrigade/compass/issues/201.
Not perfect, but better than nothing.
=> Redirect user if missing auth cookie

src/pages/students/[student_id].tsx
=> Fix getActiveStudentIep frontend query to stop calling if call failed

src/backend/routers/case_manager.test.ts, src/backend/routers/case_manager.ts, src/components/subgoal/Subgoal-Assignment-Modal.tsx, src/components/table/table.tsx, src/pages/staff/[user_id].tsx
Add self to staff list & disable `unassign Para` when viewing self.
- **All Staff page View:**
- **View of Self:**
- **Original - Individual para page view:**
=> Assign self to staff list

package-lock.json, src/components/table/table.tsx
Before, it said 'Add student' even on the staff page
=> Use the type param in the table, to ensure we refer to staff on the staff page.

src/pages/staff/[user_id].tsx, src/pages/students/[student_id].tsx
=> changed placeholder to defaultValue on forms for edit student and edit staff

src/backend/routers/user.test.ts, src/backend/routers/user.ts
=> Add a 'isCaseManager' function to user

src/components/design_system/dropdown/Dropdown.module.css, src/components/design_system/dropdown/Dropdown.tsx, src/pages/settings.tsx
=> Create reusable template for dropdown menu

src/pages/students/index.tsx
There is now an instructive alert that will appear when the wrong email format is submitted.
(see issue #313 for the previous state)
Consulted trpc docs, but didn't find a more straightforward way to access the message for the error- that is a potential area for improvement.
=> Resolution to Issue #313: Error alert for invalid email entry

package.json, src/backend/routers/_app.ts, src/backend/routers/public.ts, src/backend/routers/routes.test.ts, src/backend/trpc.ts
To verify:
- pull code
- run tests
- -> they pass
=> Adds  test that ensures all api routes are protected

src/components/iep/Iep.tsx, src/pages/students/[student_id].tsx
several warnings and errors were thrown in the console during student edit if the student has no iep data
=> fix: cleanup errors and warnings

.github/workflows/deploy.yml, .github/workflows/pr.yml
There are some dependabot PRs related to updated Github actions... this PR updates all of them...
=> [Closes #475] Bump github action dependencies with open dependabot PRs
