- .env.example
- src/backend/auth/adapter.ts
- src/backend/db/migrations/1_initial-migrations.sql
- src/backend/db/zapatos/schema.d.ts
- src/pages/api/auth/[...nextauth].ts
This configures NextAuth to use a custom, persisted adapter instead of the default stateless JWT one.
This lays the groundwork for authenticating incoming requests and attaching them to a user.
> Add persistent session-based auth adapter

- README.md
Moved Windows Command `git config --global core.autocrlf false` to top prior to checking out code (As doing this after checkout will cause git to determine it as "modified" file in windows, so must do git setting prior to checkout)
> Updated README.md ordering for windows user

- .gitignore
- terraform/README.md
- terraform/compass_module/alb.tf
- terraform/compass_module/ecr.tf
- terraform/compass_module/ecs.tf
- terraform/compass_module/iam.tf
- terraform/compass_module/main.tf
- terraform/compass_module/networking.tf
- terraform/compass_module/s3.tf
- terraform/compass_module/variables.tf
- terraform/staging/main.tf
In this iteration, the secrets are read from a `staging.env` file in an S3 bucket. This level of security and convenience is likely ok for now.
Additionally, the current iteration launches the tasks in a public subnet, so as to be able to read the Docker images from the ECR. The individual instances themselves are still not accessible due to the their security group settings. If we want to launch them in a private subnet, then we would need to create VPC endpoints - the complexity might not be worth the benefits.
Postgres setup in AWS will follow in a separate PR.
#60
> Terraform configuration for ECS and related services.

- src/pages/_app.tsx
All calls are logged in development, and only errors are logged in production.
> Log trpc calls

- src/pages/paras/[user_id].tsx
- src/pages/students/[student_id].tsx
- src/pages/students/iep.tsx
The two paths are identical for NextJs. One other benefit of this change is that we reduce the number of files called "index.tsx" which makes them easier to find in the IDE :)
> Flatten directory structure by moving dir/[id]/index.tsx -> dir/[id].tsx

- package.json
Tests are currently failing for node 20
> Restrict the node versions to <20.0.0 for Compass.

- ava.config.js
- package-lock.json
- package.json
The previous loader didn't work in Node.js v20.
> Transpile tests using a require-based loader instead of --experimental-loader

- package-lock.json
- package.json
This fixes the `high` vulnerabilities, but still have a few moderate ones remaining related to eslint-config-next
> npm audit fix. Needed updating versions of aws-sdk deps

- src/middleware.ts
Apparently next auth uses a different cookie name for HTTPS origins.
> Fix staging login redirect loop

- src/components/table/table.tsx
Referencing issue #232. I adjusted the specification of the empty state so Staff page shouldn't be affected by Student's list empty state anymore.
**Before:**
**After**:
> BUG: Empty staff list shows student's empty state #232

- src/components/subgoal/Subgoal-Assignment-Modal.tsx
- src/components/subgoal/Subgoal.tsx
Closes https://github.com/sfbrigade/compass/issues/236.
Demo:
https://github.com/sfbrigade/compass/assets/7410405/0b374b13-3899-45de-a05b-7e439b6596d5
> Add para assignment dialog

- src/backend/routers/iep.ts
- src/components/subgoal/Subgoal-Assignment-Modal.module.css
- src/components/subgoal/Subgoal-Assignment-Modal.tsx
- src/components/subgoal/Subgoal.tsx
Added some CSS and beginning of conditional rendering for second half of modal.
> Added description to assign to benchmark flow

- src/components/navbar/NavBar.tsx
- src/components/navbar/Navbar.module.css
> Add highlight to navbar showing current tab selected

- src/backend/routers/case_manager.ts
- src/components/layout/Layout.module.css
- src/components/layout/Layout.tsx
- src/pages/staff/[user_id].tsx
- src/styles/StaffPage.module.css
- src/styles/StudentPage.module.css
Staff page: ticket #200 
- Build staff page, emulating student page.
- In user_id.tsx, add edit/view states with Save and Cancel buttons, display email address, add form with inputs/placeholders, refactor Archive button to match Student archive, add Modal to open when Archive button pressed.
- Create StaffPage.module.css file.
- Add editPara authenticated procedure in case_manager.ts so that case_manager can edit para name and email.
- Add mainStaff to Layout.module.css to have same bg color as student page.
- Update Layout.tsx to include logic to check if user_id for bg color.
- Add handleEditPara function and editMutation to user_id.tsx.
- Add logic to editPara to determine if userId is same as para_id to prevent para from editing another para while letting them edit themself.
> Staff page

- src/components/taskCard/taskCard.tsx
- src/pages/benchmarks/[benchmark_id]/index.tsx
#249
- Added new state `TrialAdded` to ensure the trial is only added once.
- Fix logic for task cards having 100% after each submission.
> Fix error - create trial twice & task card % logic

- src/components/design_system/button/Button.module.css
- src/components/table/Table.module.css
- src/components/table/table.tsx
- src/pages/settings.tsx
- src/styles/globals.css
#293
Font size at .875rem [14px] at screens lower than 480px.
Font size at .9375rem [15px] at screens above 480px.
Font size at 1rem [16px] at screens above 768px.
Add reusable font-size classes including small and x-small sizes.
Following [Typography chart ](https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Designs?type=design&node-id=12388-48833&mode=design&t=ghaGyca0JE0N57m0-4)
> Add scalable font size to global and adjust font size of other files.

- src/backend/routers/case_manager.ts
- src/backend/routers/student.test.ts
- src/backend/routers/student.ts
- src/components/design_system/button/Button.module.css
- src/pages/students/[student_id].tsx
- src/styles/StudentPage.module.css
This closes ticket #212 
* Iep layout is closer to design systems layout
* Button for archive is moved out to Student instead of inside edit.
* Edit items have been put in order of creation
* Edit IEP options entered into form (CSS will be finalized/updated with Modal creating in next ticket)
* Edit IEP trpc function created
* Ava test for editIep created and passed
> Added editIEP to the front and back end and wrote test. Future builds will include these in a modal.

- src/pages/students/[student_id].tsx
Link to issue:
https://github.com/sfbrigade/compass/issues/314
Styling will be in a separate issue/PR
> Creation of Edit Student Modal- Issue #314

- src/backend/lib/db_helpers/case_manager.ts
- src/backend/lib/db_helpers/para.ts
- src/backend/routers/case_manager.test.ts
- src/backend/routers/case_manager.ts
- src/backend/routers/para.ts
- src/pages/staff/index.tsx
Replaces two subsequent trpc calls with one, with the logic for that call broken out into several functions in a new helper file. Calls for the creation of the invitation email but does not await the result of the promise, so email failures will no longer hold up a response from being sent to the client. Adding staff should be clear and straightforward for a user, but any Postgres error that causes the mutation to fail (duplicate email) could still benefit from a toast notification as to the cause of the error.
> Fix add staff

- src/components/design_system/button/Button.module.css
- src/components/layout/Layout.tsx
- src/components/navbar/NavBar.tsx
- src/components/taskCard/TaskCard.module.css
- src/components/taskCard/taskCard.tsx
- src/pages/benchmarks/index.tsx
- src/styles/Box.module.css
#303
Following [This Design](https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Designs?type=design&node-id=12340-23722&mode=design&t=CFJtAF1N0loNBF5Q-4) for Data Collection
- Added Assign Tab in Nav bar
- Adjusted icons
- Edit Task Cards
- Added Toggle View for CM & Para for Benchmarks page only
- Add Placeholders for Search, Filter, Sort
Also, nothing has been done to the data collection page yet. Waiting for the benchmark creation to be completed to use the data for the instructions page.
https://github.com/sfbrigade/compass/assets/104481165/cb8aae01-7f15-45ea-abb4-96fe173c4ba0
> Add Nav tab for benchmarks

- src/backend/lib/db_helpers/case_manager.ts
- src/backend/routers/case_manager.test.ts
- src/backend/routers/case_manager.ts
In reference to issue #327, moves bulk of logic from routers/case_manager `addStudent` procedure over to lib/db_helpers/case_manager `createAndAssignStudent` function. Also creates specific errors, which are thrown by the new function to allow better information for the client to display. There is no client aspect to this PR, though making that final connection could easily be added to this PR. Also adds several additional tests on the routers/case_manager.test.ts to ensure that the correct errors are being thrown in the correct circumstances.
> Fix add student error logic

- src/pages/students/[student_id].tsx
Change to allow for proper check of the min IEP date.
Now, the end IEP dates are greyed out to prevent selection of a date that is less than the start IEP date.
Before:
After:
> Fixed check for iep end date- resolution to [ENG] #316 issue

- src/components/design_system/modal/CompassModal.module.css
- src/pages/students/[student_id].tsx
See issue here: https://github.com/sfbrigade/compass/issues/334
Import of the custom/project Modal component was not occurring.
Note that the staff page does not utilize the same Modal, so the reference doesn't need updates.
Co-authored-by: Yun Whitman <savannahwhitman1@gmail.com>
> Resolution of any value error within [student_id] - Issue #334

- src/backend/db/migrations/1_initial-migrations.sql
- src/backend/routers/student.test.ts
Added check to IEP table schema in initial_migrations to make sure end date is greater than or equal to start date. created test in student.test.ts to check that having a smaller end date will throw an error when creating a new IEP or editing an IEP.
> added check and test for IEP end dates

- README.md
- package.json
- src/backend/db/lib/index.ts
- src/backend/db/lib/seed.ts
- src/backend/scripts/seed-database.ts
Seed script has been added to populate tables with test data.
One can use npm run db:seed to add three students and one staff member to the database.
> Closes #365: Added Seed Script

- src/pages/students/[student_id]/goals/[goal_id]/create.tsx
I found saw warnings when loading the "Create Benchmark" page, captured in this file:
[369_browser_console_warnings.log](https://github.com/user-attachments/files/16606471/369_browser_console_warnings.log)
These three appear to be caused by the Stepper expecting the icon components exp:
```
hydration-error-info.js:63 Warning: Received `false` for a non-boolean attribute `completed`.
hydration-error-info.js:63 Warning: Received `true` for a non-boolean attribute `active`.
hydration-error-info.js:63 Warning: Received `false` for a non-boolean attribute `error`.
```
This warning appears to be caused by the value property of a `TextArea` defaulting to `null`:
```
hydration-error-info.js:63 Warning: `value` prop on `textarea` should not be null. Consider using an empty string to clear the …
```
> Fix #369: Fixed Javascript console warnings on Create Benchmark page

- src/backend/db/lib/seed.test.ts
- creates a test db
- runs 'seedfile' from src/backend/db/lib/seed.ts
- queries the db for both students and users
- asserts that there are >0 students and users
- closes #387
> adds a test that runs the db seed, making sure it's compatible with latest schema

- src/components/layout/Layout.module.css
- src/components/layout/Layout.tsx
Fix to only add the `margin-left: 200px` needed for the navigation side bar on pages other than the sign-in page.
Fixes #403.
> Don't add 200px left margin for toolbar on sign-in page.

- .github/workflows/pr.yml
- .prettierrc.json
- package-lock.json
- package.json
- src/backend/scripts/run-with-gcp-metadata.ts
- src/components/design_system/button/Button.module.css
- src/components/table/table.tsx
- src/components/taskCard/taskCard.tsx
- src/pages/benchmarks/[benchmark_id]/index.tsx
We've historically had issues with prettier failing in the build pipeline for unknown reasons. This is likely some kind of versioning issue. Examining outputs of running v2.8.8 vs v.3.3.3 confirms different output, which can account for the issue as described in #437. However, we still don't know why the issue is intermittent nor why it sometimes seems to differ between environments. Forcing all versions of prettier to be v.3 or above and our code to conform to its defaults/our config is the goal of this PR.
This PR does the following:
- merges two prettier config files into one
- adds config property `trailingComma: "es5"` to preserve as much formatting as possible when going from v2 (where it's the default) and v3 (where `trailingComma: "all"` is the default instead)
- upgrades prettier …
> Attempt to fix intermittent prettier issues

- src/backend/db/migrations/2_add-uniqueness-constraint-on-tasks.sql
- src/backend/db/zapatos/schema.d.ts
- src/backend/lib/db_helpers/case_manager.ts
- src/backend/routers/case_manager.ts
- src/backend/routers/iep.test.ts
- src/backend/routers/iep.ts
- src/components/benchmarks/BenchmarkAssignmentModal.tsx
Closes #439
Add uniqueness constraint on tasks to prevent assigning the same
benchmark (subgoal) to the same para (assignee).
What remains to be done is #450 , the frontend should indicate that a task has already been assigned to a given assignee and not allow the option to assign it to them again.
> Feat: add uniqueness constraint to task table

- README.md
Make it more clear you need to log in with Google OAuth to generate the first user before you can run the seed script.
> Update README.md to make clear to login before seeding

- src/backend/db/lib/seed.ts
- src/backend/routers/para.ts
- src/pages/benchmarks/index.tsx
- src/types/global.ts
This PR adds sorting functionality on the front end for the Assigned page. It does so by adding a new button (simple stand-in for current placeholder) that toggles between name ascending and descending sort. It partly addresses #424.
Note that each interaction currently forces a rerender, so we will want to revisit in future to improve perf (through either `useEffect()` and/or server-side sorting). This is good enough for POC, however.
Also note that we will likely need to replace the button with a sorting dropdown to incorporate other sort properties.
> add sort by name to assigned page

- src/pages/benchmarks/[benchmark_id]/index.tsx
Behavior described in issue #468 is no longer occuring. 
Source of the problem was that useEffect was causing a rerender of the benchmark component in development.
> Fixes #468 (extra trial data) - update to prevent rerender

- src/backend/routers/iep.ts
- src/pages/benchmarks/[benchmark_id]/instructions.tsx
Materials List is no longer hard-coded, and pulls from the inputted data.
> Fixes #492 Materials List
